#!/usr/bin/python

# -------------------------------------------------#
#               DO NOT EDIT THIS FILE              #
# -------------------------------------------------#
# If you wish to modify the pins used, please edit #
#    /etc/hypnic.conf                              #
#--------------------------------------------------#

from configparser import ConfigParser
import sys
import time
import RPi.GPIO as GPIO

# first read the current config
parser = ConfigParser()
parser.read('/etc/hypnic.conf')

SAFE_PIN = parser.getint("pins", "safe_pin")

if (len(sys.argv) > 1):
    arg = str(sys.argv[1])
    if (arg == "halt" or arg == "poweroff"):
        #logging.info('Request to halt or shutdown')
        GPIO.setmode(GPIO.BCM)
        GPIO.setup(SAFE_PIN, GPIO.OUT)
        #logging.warning('Setting safe pin high')
        GPIO.output(SAFE_PIN, GPIO.HIGH)
        time.sleep(10)
